import type { Metadata } from "next";
import Experience from "../components/background/Sphere";
import './global.css'
import Nav from "../components/nav/Nav";
import SmoothScrolling from "../components/smoothScroll/SmoothScroll";
import NoiseEffect from "../components/grain/NoiseEffect";
import GlassEffect from "../components/grain/GlassEffect";
import Footer from "../components/footer/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html>
  <body>
    <div className="page-container">
      <SmoothScrolling>
        <NoiseEffect />
        <Experience />
        <GlassEffect />
        <Nav />
        <main className="main-content">{children}</main>
        <Footer />
      </SmoothScrolling>
    </div>
  </body>
</html>
  );
}
