import type { Metadata } from "next";
import Experience from "../components/background/Sphere";
import './global.css'
import Nav from "../components/nav/Nav";
import SmoothScrolling from "../components/smoothScroll/SmoothScroll";
import NoiseEffect from "../components/grain/NoiseEffect";
import GlassEffect from "../components/grain/GlassEffect";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <SmoothScrolling>
          <Nav />
          <NoiseEffect/>
          {children}
          <Experience meshRef={null} />
          <GlassEffect/>
        </SmoothScrolling>
      </body>
    </html>
  );
}
