import type { Metadata } from "next";
import GrainEffect from "../components/grain/GrainEffect";
import Experience from "../components/background/Sphere";
import './global.css'
import Nav from "../components/nav/Nav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Nav/>
        {children}
      <GrainEffect/>
      <Experience meshRef={null}/>
      </body>
    </html>
  );
}
